spring:
  application:
    name: mmrTest

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  messages:
    encoding: UTF-8

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

riot:
  api:
    key: ${RIOT_API_KEY:${RIOT_API_KEy:}}

dev:
  allowlist:
    enabled: false
    riotIds:
      - "guny#kr1"
      - "욕설멈춰i#kr1"
      - "Lune silencieuse#KR2"
      - "hideonbush#kr1"
score:
  calibration-log-enabled: true
